### ISSUE TITLE
MessageToDict() got an unexpected keyword argument 'including_default_value_fields'

### ISSUE THREAD

**Issue by niteshy** [cloudera/dbt-hive#135]
After updating the dbt-core to 1.5.10, all the tests are broken with the following stack trace 
```
 def msg_to_dict(msg: EventMsg) -> dict:
        msg_dict = dict()
        try:
>           msg_dict = MessageToDict(
                msg, preserving_proto_field_name=True, including_default_value_fields=True  # type: ignore
            )
E           TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'
```
More details https://gist.github.com/niteshy/9eca53865ae1749aa2dfd91ff20b265f

This has happened because of incompatible version of protobuf >5 with dbt-core
